### PR TITLE
Fixes #193: Don't fail if the browser doesn't report a country

### LINKED ISSUE #193: Kann Land nicht festlegen
Im Auswahlfenster wird mir kein Land angezeigt und unten auf der Seite kann ich das Land auch nicht ändern.
grafik
grafik

### PR DESCRIPTION
**Pull request by baltpeter**

### CODE REVIEW

**Comment by pyfisch** [comment]
:+1: Funktioniert alles wie erwartet.

File: src/general.js [hunk 1]
```diff
@@ -78,7 +78,7 @@ function guessUserCountry() {
```
Comment (zner0L) [inline src/general.js]: We should also try to fallback to the language if we can not get the country from the language string, because only a language is reported (e.g. `de` instead of `de-de` as seen in #193).
