### PR TITLE
Fixes #253: Implement async newRequest method in the button also 

### LINKED ISSUE #253: Wizard regressions
In wizard mode, the request is cleared, even though some companies are still in the loop.

### PR DESCRIPTION
**Pull request by zner0L**

### CODE REVIEW

File: src/Utility/request-generator-replacers.js [hunk 1]
```diff
@@ -42,7 +42,13 @@ const replacer_factory = that => ({
...
             onClick={() => {
                 if (!that.state.request.done) that.confirmNewRequest();
-                else that.newRequest();
+                else
+                    that.newRequest().then(() => {
+                        // We are in batch mode, move to the next company.
+                        if (that.state.batch && that.state.batch.length > 0) {
+                            that.setCompanyBySlug(that.state.batch.shift()).then(that.renderLetter);
+                        } else that.renderLetter();
+                    });
```
Comment (baltpeter) [inline src/Utility/request-generator-replacers.js]: This should be wrapped in curly braces. But in the interest of getting this important fix merged quickly, I'll let that slide…
